### ISSUE TITLE
Navbar for Desktop + Mobile

### ISSUE THREAD

**Issue by RobbieZhuang** [SESoc/public-website#18]
Build navbar experience for desktop + mobile

Only have **Home, About and Events** links in the navbar (remove Get Involved and Blog for now)
- Left align logo to match the beginning of the body content
- Right align the navbar options to the end of the body content

**Desktop:**
<img src="https://user-images.githubusercontent.com/14525856/81853887-16fc7e80-952b-11ea-9e79-173af5de2212.png" width="600px">

**Mobile:**
<img src="https://user-images.githubusercontent.com/14525856/81853893-18c64200-952b-11ea-969f-b0cf9ef8bc0a.png" width="200px">

**Comment by yingninggui** [comment]
<img width="1440" alt="Screen Shot 2020-05-11 at 1 40 03 PM" src="https://user-images.githubusercontent.com/18473516/81593120-f8f91780-938c-11ea-854b-629980e0f794.png">
<img width="1440" alt="Screen Shot 2020-05-11 at 1 40 10 PM" src="https://user-images.githubusercontent.com/18473516/81593122-f991ae00-938c-11ea-8b44-1e3f9fd8b142.png">
not sure if y'all are already doing this but any chance we can vertically align the nav bar with the headings ?

**Comment by RobbieZhuang** [comment]
Yup, planning to follow the mocks. It'll be ready for launch ^^
![About](https://user-images.githubusercontent.com/14525856/81611956-fe188f80-93a9-11ea-9483-b60a5f0ceab1.png)
