### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by SDobrik** [SESoc/public-website#3]
Modify Home Page to match updated designs
- **Don't build the footer** - In seperate PR #48  
- Grey boxes will contain illustrations by Ariel (rough drafts by Wed, May 6, final by May 10)
- `Check out all upcoming events`  and `Check out more content` should be clickable and link to events and blog (previously news) pages respectively.
- Content: https://docs.google.com/document/d/1V0nHFhP-T3aG6PavJSltaWyYsOCeK-yzVuWRQX8V0Zw/edit
- Font Desktop:
   <img src=
"https://user-images.githubusercontent.com/14525856/80932662-6eae2380-8d8e-11ea-983f-5225066e75fe.png" width="600">
   - i.e. the `Software Engineering Society brings the SE student community together.` message is 54px Poppins Medium
- Font Mobile:
   <img src="https://user-images.githubusercontent.com/14525856/80932791-0a3f9400-8d8f-11ea-897c-026a6dc480de.png" width="600">
- Colours:
   <img src="https://user-images.githubusercontent.com/14525856/80931881-9f8c5980-8d8a-11ea-9cb0-c671caff94d1.png" width="200">

**Desktop**
<img src="https://user-images.githubusercontent.com/14525856/80997779-d5bfec80-8e0f-11ea-99ac-57fc5d6f419f.png" width="600">
**Mobile**
<img src="https://user-images.githubusercontent.com/14525856/80997805-db1d3700-8e0f-11ea-8c34-11d03b06d5df.png" width="200">

--- 
**Previous Work:**
Add the following components to /home
- Welcome + description: with hero image
- news component
- events component

<img src="https://user-images.githubusercontent.com/14525856/79908687-ac539980-83e9-11ea-91bc-28638f06f236.png" width="200">

**Comment by tawnyzhao** [comment]
I'm working on the home page here: 
https://github.com/SESoc/public-website/pull/26
