### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by RobbieZhuang** [SESoc/public-website#41]
Please see at the designs on [Figma](https://www.figma.com/file/C5UzoDuB64dMQgUQqDLRTR/SE-Society-Website) for reference as to how much text is required. Msg @RobbieZhuang with questions.

**- Home Page**
   - Welcome blurb (2-3 sentences)
<img width="400" alt="Screen Shot 2020-04-28 at 8 24 30 PM" src="https://user-images.githubusercontent.com/14525856/80550554-70db4100-898e-11ea-92b7-6be52900e9be.png">

- Council Page
   - Council blurb (2 sentences) i.e. what do we do (Council page)
   - How students can attend general meetings (1 sentence)
<img width="522" alt="Screen Shot 2020-04-28 at 8 25 08 PM" src="https://user-images.githubusercontent.com/14525856/80550598-9c5e2b80-898e-11ea-9349-26152b133d27.png">

**Comment by yingninggui** [comment]
copy: https://docs.google.com/document/d/1V0nHFhP-T3aG6PavJSltaWyYsOCeK-yzVuWRQX8V0Zw/edit
