### ISSUE TITLE
Get Involved Page

### ISSUE THREAD

**Issue by SDobrik** [SESoc/public-website#6]
Task Breakdown

- [ ] Complete the `Get Involved` section for desktop & mobile
- [ ] Add a route in app.jsx
- [ ] Figure out where we're going to store meeting PDFs
- [ ] Create a meeting notes component and add the `Meetings` section for desktop & mobile

PDF of agenda and minutes for the SE Society's council meetings
    - https://drive.google.com/drive/folders/1U0IEIHzhV5oJIspB0fyf9H9zdP0w-o9t?usp=sharing

**Desktop**
<img src="https://user-images.githubusercontent.com/14525856/82738282-5bd2a300-9ceb-11ea-8e46-0028c8d4cf79.png" width="600px">
**Mobile**
<img src="https://user-images.githubusercontent.com/14525856/82738287-5d9c6680-9ceb-11ea-9f82-e916ed212bde.png" width="200px">

**Comment by jenniferwills** [comment]
I think PDF minutes would be better than the Google Doc versions. Google Docs we need to add public viewing permissions to and take longer to load, and PDFs could just be downloaded/opened and the minutes should not be changing after the fact so we don't need to be giving out editable versions

**Comment by RobbieZhuang** [comment]
Good point, I updated the description.
